services:
  - type: web
    name: italianbistro
    env: ruby
    repo: https://github.com/adrianvalenz/italianbistro
    buildCommand: bundle install && yarn install && bin/bridgetown frontend:build
    startCommand: bin/bridgetown start
    envVars:
      - key: BRIDGETOWN_ENV
        value: production

